/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GOOGLE_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "REPLICATE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TeachingTalesApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TeachingTalesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}