import Replicate from 'replicate';
import { REPLICATE_CONFIG } from '@/lib/config';
import { AIServiceError } from './types';

// Try to load server config if available (only in server context)
let serverConfig: any;
try {
  if (typeof window === 'undefined') {
    serverConfig = require('@/lib/config.server').REPLICATE_SERVER_CONFIG;
  }
} catch (e) {
  // Server config not available, use regular config
}

/**
 * Client class for interacting with Replicate AI API
 * 
 * Provides a robust interface to Replicate's image generation models with built-in
 * error handling, retry logic, and educational content safety features.
 * 
 * @example
 * ```typescript
 * const client = new ReplicateClient();
 * const imageUrl = await client.generateImage('A friendly dragon reading a book');
 * ```
 */
export class ReplicateClient {
  private replicate: Replicate;

  /**
   * Creates a new ReplicateClient instance
   */
  constructor() {
    const config = serverConfig || REPLICATE_CONFIG;
    
    if (!config.API_KEY) {
      throw new AIServiceError('Replicate API key not configured');
    }

    this.replicate = new Replicate({
      auth: config.API_KEY,
    });
  }

  /**
   * Generate an educational story illustration using Replicate AI
   * 
   * Creates child-safe, educational images suitable for story illustrations.
   * The prompt is automatically enhanced with safety guidelines and educational
   * content specifications.
   * 
   * @param prompt - Description of the image to generate
   * @param options - Optional generation parameters
   * @returns Promise resolving to the generated image URL
   * @throws {AIServiceError} When generation fails or times out
   */
  async generateImage(
    prompt: string,
    options: {
      width?: number;
      height?: number;
      gradeLevel?: string;
    } = {}
  ): Promise<string> {
    try {
      // Enhance prompt for educational content safety
      const enhancedPrompt = this.enhancePromptForEducation(prompt, options.gradeLevel);
      

      const input = {
        prompt: enhancedPrompt,
        width: options.width || 1024,
        height: options.height || 768,
        num_outputs: 1,
        guidance_scale: 7.5,
        num_inference_steps: 4, // Fast generation with Flux Schnell
        seed: Math.floor(Math.random() * 1000000),
      };

      const config = serverConfig || REPLICATE_CONFIG;
      const output = await this.replicate.run(config.MODEL_NAME, { input });
      
      if (!output || !Array.isArray(output) || output.length === 0) {
        throw new AIServiceError('No image generated by Replicate');
      }

      const imageUrl = output[0] as string;
      
      return imageUrl;

    } catch (error) {
      console.error('❌ Image generation failed:', error);
      
      if (error instanceof AIServiceError) {
        throw error;
      }
      
      throw new AIServiceError(
        `Image generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error instanceof Error ? error : undefined
      );
    }
  }

  /**
   * Enhance the prompt for educational content and safety
   * 
   * Adds safety guidelines, educational context, and appropriate style
   * specifications to ensure generated images are suitable for children.
   * 
   * @param basePrompt - Original image description
   * @param gradeLevel - Target grade level for age-appropriate content
   * @returns Enhanced prompt with safety and educational guidelines
   * @private
   */
  private enhancePromptForEducation(basePrompt: string, gradeLevel?: string): string {
    // Base safety and style guidelines
    const safetyTerms = [
      'children\'s book illustration',
      'educational',
      'friendly',
      'colorful',
      'safe for children',
      'cartoon style',
      'wholesome'
    ];

    // Grade-level specific enhancements
    const gradeEnhancements: Record<string, string> = {
      'K-1': 'simple shapes, bright primary colors, very friendly characters',
      '2-3': 'clear details, engaging characters, vibrant colors',
      '4-5': 'detailed illustration, adventure themes, rich colors',
      '6-8': 'sophisticated art style, dynamic composition, mature themes appropriate for middle school'
    };

    const gradeSpecific = gradeLevel && gradeEnhancements[gradeLevel] 
      ? gradeEnhancements[gradeLevel] 
      : 'age-appropriate content';

    // Combine all elements
    const enhancedPrompt = [
      basePrompt,
      ...safetyTerms,
      gradeSpecific,
      'no scary or inappropriate content',
      'positive and uplifting mood',
      'high quality digital art'
    ].join(', ');

    return enhancedPrompt;
  }

  /**
   * Test the connection to the Replicate service
   * 
   * @returns Promise resolving to true if connection is successful
   */
  async validateConnection(): Promise<boolean> {
    try {
      // Test with a simple, safe prompt
      await this.generateImage('A simple blue circle', { width: 256, height: 256 });
      return true;
    } catch (error) {
      console.error('Replicate connection test failed:', error);
      return false;
    }
  }
}
