/**
 * @fileoverview Phase 3 → Phase 4 Integration Tests
 * 
 * Tests the complete end-to-end flow from Phase 3 question generation
 * to Phase 4 assessment creation, ensuring seamless integration between phases.
 */

import { QuestionGenerationService } from '@/lib/ai/question-generation-service';
import { AssessmentService } from '../assessment-service';
import { createAssessmentTest } from '@/lib/api/qti-client';
import { FEATURE_FLAGS } from '@/lib/config';
import type { SectionQuestionsResult, EnhancedComprehensionQuestion } from '@/lib/ai/types';

// Mock external dependencies
jest.mock('@/lib/ai/question-generation-service');
jest.mock('@/lib/api/qti-client');
jest.mock('@/lib/config', () => ({
  FEATURE_FLAGS: {
    QTI_ASYNC_ASSESSMENTS_ENABLED: true,
    QTI_SPLIT_GENERATION_ENABLED: true
  }
}));

describe('Phase 3 → Phase 4 Integration', () => {
  let questionService: jest.Mocked<QuestionGenerationService>;

  const mockPhase3Questions: EnhancedComprehensionQuestion[] = [
    {
      id: 'section_0_q1',
      type: 'multiple_choice',
      question: 'What magical ability did the crystal possess?',
      options: ['Invisibility', 'Mind reading', 'Glowing with ancient wisdom', 'Time travel'],
      correct: 2,
      explanation: 'The text describes the crystal as glowing with blue light and whispering ancient secrets.',
      questionType: 'comprehension',
      difficultyLevel: 3
    },
    {
      id: 'section_0_q2',
      type: 'multiple_choice', 
      question: 'How might the protagonist feel upon discovering the crystal?',
      options: ['Terrified', 'Curious and excited', 'Angry', 'Indifferent'],
      correct: 1,
      explanation: 'Given the magical nature of the discovery, curiosity and excitement would be natural responses.',
      questionType: 'inference',
      difficultyLevel: 4
    }
  ];

  const mockPhase3Response: SectionQuestionsResult = {
    sectionIndex: 0,
    questions: mockPhase3Questions,
    metadata: { 
      generationTimeMs: 1200, 
      modelUsed: 'gemini-2.0-flash',
      retryCount: 0,
      validationPassed: true
    }
  };

  const mockQTIResponse = {
    id: 'integration-assessment-123',
    identifier: 'story-integration-test-story-section-0-async',
    title: 'Integration Test Story - Section 1 Assessment (Async)',
    description: 'Async-generated comprehension questions for section 1',
    status: 'active',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    metadata: expect.any(Object)
  };

  beforeEach(() => {
    jest.clearAllMocks();
    
    // Mock QuestionGenerationService
    questionService = new QuestionGenerationService() as jest.Mocked<QuestionGenerationService>;
    questionService.generateQuestionsForSection = jest.fn().mockResolvedValue(mockPhase3Response);
    
    // Mock QTI client
    (createAssessmentTest as jest.Mock).mockResolvedValue(mockQTIResponse);
    
    // Ensure feature flags are enabled
    (FEATURE_FLAGS as any).QTI_ASYNC_ASSESSMENTS_ENABLED = true;
    (FEATURE_FLAGS as any).QTI_SPLIT_GENERATION_ENABLED = true;
  });

  it('should create assessments from questions generated by Phase 3 API', async () => {
    // Step 1: Generate questions using Phase 3
    const sectionInput = {
      sectionContent: 'Ruby the fox discovered a mysterious crystal deep in the enchanted forest. The crystal pulsed with ethereal blue light and seemed to whisper ancient secrets that only she could hear.',
      sectionIndex: 0,
      gradeLevel: '4-5' as const
    };

    const questions = await questionService.generateQuestionsForSection(sectionInput);
    
    // Verify Phase 3 generation
    expect(questionService.generateQuestionsForSection).toHaveBeenCalledWith(sectionInput);
    expect(questions.sectionIndex).toBe(0);
    expect(questions.questions).toHaveLength(2);
    expect(questions.metadata.validationPassed).toBe(true);
    
    // Step 2: Convert to Phase 4 format using the adapter
    const assessmentMetadata = {
      storyId: 'integration-test-story',
      stimulusId: 'integration-test-stimulus',
      storyTitle: 'Integration Test Story',
      universe: 'Magical Forest',
      character: 'Ruby the Fox',
      spark: 'Mysterious Crystal Discovery',
      gradeLevel: '4-5' as const,
      studentId: 'test-student-123'
    };

    const assessmentInput = AssessmentService.prepareSectionAssessmentFromAPI(
      questions,
      sectionInput.sectionContent,
      assessmentMetadata
    );

    // Verify adapter conversion
    expect(assessmentInput).toEqual({
      sectionIndex: 0,
      sectionContent: sectionInput.sectionContent,
      questions: mockPhase3Questions,
      metadata: assessmentMetadata
    });
    
    // Step 3: Create assessment using Phase 4
    const assessments = await AssessmentService.createSectionAssessmentsFromQuestions([assessmentInput]);
    
    // Verify Phase 4 assessment creation
    expect(assessments).toHaveLength(1);
    expect(assessments[0].sectionIndex).toBe(0);
    expect(assessments[0].assessmentId).toBe('integration-assessment-123');
    expect(assessments[0].metadata.questionCount).toBe(questions.questions.length);
    
    // Verify QTI client was called with enhanced data from both phases
    expect(createAssessmentTest).toHaveBeenCalledWith(
      expect.objectContaining({
        identifier: 'story-integration-test-story-section-0-async',
        title: 'Integration Test Story - Section 1 Assessment (Async)',
        metadata: expect.objectContaining({
          // Phase 4 metadata
          generationMethod: 'async-split',
          createdWithPhase: 'phase-4',
          assessmentType: 'section-comprehension-async',
          questionGenerationAPI: '/api/generate-questions',
          
          // Story metadata
          storyId: 'integration-test-story',
          universe: 'Magical Forest',
          character: 'Ruby the Fox',
          
          // Enhanced questions with Phase 3 enhancements
          questions: expect.arrayContaining([
            expect.objectContaining({
              id: 'section_0_q1',
              questionType: 'comprehension',
              difficultyLevel: 3,
              sequence: 1
            }),
            expect.objectContaining({
              id: 'section_0_q2',
              questionType: 'inference', 
              difficultyLevel: 4,
              sequence: 2
            })
          ])
        })
      })
    );
  });

  it('should handle multi-section integration flow', async () => {
    // Mock multiple section responses from Phase 3
    const section1Response = { ...mockPhase3Response, sectionIndex: 1 };
    questionService.generateQuestionsForSection
      .mockResolvedValueOnce(mockPhase3Response) // Section 0
      .mockResolvedValueOnce(section1Response);  // Section 1

    const sections = [
      {
        content: 'Section 0 content: Ruby discovers the crystal...',
        index: 0
      },
      {
        content: 'Section 1 content: The crystal begins to glow brighter...',
        index: 1
      }
    ];

    // Generate questions for multiple sections
    const questionPromises = sections.map(section => 
      questionService.generateQuestionsForSection({
        sectionContent: section.content,
        sectionIndex: section.index,
        gradeLevel: '4-5'
      })
    );
    const questionsResults = await Promise.all(questionPromises);

    // Convert all to Phase 4 format
    const assessmentInputs = questionsResults.map(result => 
      AssessmentService.prepareSectionAssessmentFromAPI(
        result,
        sections[result.sectionIndex].content,
        {
          storyId: 'multi-section-story',
          storyTitle: 'Multi Section Story',
          universe: 'Test Universe',
          character: 'Test Character',
          spark: 'Test Spark',
          gradeLevel: '4-5',
          studentId: 'test-student'
        }
      )
    );

    // Mock multiple QTI responses
    (createAssessmentTest as jest.Mock)
      .mockResolvedValueOnce({ ...mockQTIResponse, id: 'assessment-section-0' })
      .mockResolvedValueOnce({ ...mockQTIResponse, id: 'assessment-section-1' });

    // Create assessments for all sections
    const assessments = await AssessmentService.createSectionAssessmentsFromQuestions(assessmentInputs);

    // Verify multi-section results
    expect(assessments).toHaveLength(2);
    expect(assessments[0].sectionIndex).toBe(0);
    expect(assessments[1].sectionIndex).toBe(1);
    expect(assessments[0].assessmentId).toBe('assessment-section-0');
    expect(assessments[1].assessmentId).toBe('assessment-section-1');
    expect(createAssessmentTest).toHaveBeenCalledTimes(2);
  });

  it('should handle Phase 3 generation failures gracefully', async () => {
    // Mock Phase 3 failure
    questionService.generateQuestionsForSection.mockRejectedValue(
      new Error('Phase 3 AI service temporarily unavailable')
    );

    // Attempt to generate questions
    await expect(
      questionService.generateQuestionsForSection({
        sectionContent: 'Test content',
        sectionIndex: 0,
        gradeLevel: '4-5'
      })
    ).rejects.toThrow('Phase 3 AI service temporarily unavailable');

    // Phase 4 should not be called
    expect(createAssessmentTest).not.toHaveBeenCalled();
  });

  it('should handle Phase 4 assessment creation failures after successful Phase 3', async () => {
    // Phase 3 succeeds
    const questions = await questionService.generateQuestionsForSection({
      sectionContent: 'Test content',
      sectionIndex: 0,
      gradeLevel: '4-5'
    });

    expect(questions).toBeDefined();

    // Phase 4 fails
    (createAssessmentTest as jest.Mock).mockRejectedValue(
      new Error('QTI service connection failed')
    );

    const assessmentInput = AssessmentService.prepareSectionAssessmentFromAPI(
      questions,
      'Test content',
      {
        storyId: 'test-story',
        storyTitle: 'Test Story',
        universe: 'Test',
        character: 'Test',
        spark: 'Test',
        gradeLevel: '4-5',
        studentId: 'test'
      }
    );

    // Phase 4 should fail gracefully
    await expect(
      AssessmentService.createSectionAssessmentsFromQuestions([assessmentInput])
    ).rejects.toThrow('Failed to create assessment for section 0: QTI service connection failed');
  });

  it('should preserve all Phase 3 enhanced metadata through Phase 4', async () => {
    // Mock Phase 3 response with enhanced validation metadata
    const enhancedPhase3Response: SectionQuestionsResult = {
      sectionIndex: 0,
      questions: [
        {
          ...mockPhase3Questions[0],
          validationMetadata: {
            validationPassed: true,
            warnings: ['Minor grammatical adjustment made'],
            hasTextEvidence: true
          }
        }
      ],
      metadata: {
        generationTimeMs: 1800,
        modelUsed: 'gemini-2.0-flash',
        retryCount: 1,
        validationPassed: true
      }
    };

    questionService.generateQuestionsForSection.mockResolvedValue(enhancedPhase3Response);

    // Generate and convert
    const questions = await questionService.generateQuestionsForSection({
      sectionContent: 'Test content',
      sectionIndex: 0,
      gradeLevel: '4-5'
    });

    const assessmentInput = AssessmentService.prepareSectionAssessmentFromAPI(
      questions,
      'Test content',
      {
        storyId: 'test-story',
        storyTitle: 'Test',
        universe: 'Test',
        character: 'Test',
        spark: 'Test',
        gradeLevel: '4-5',
        studentId: 'test'
      }
    );

    await AssessmentService.createSectionAssessmentsFromQuestions([assessmentInput]);

    // Verify enhanced metadata is preserved in QTI call
    expect(createAssessmentTest).toHaveBeenCalledWith(
      expect.objectContaining({
        metadata: expect.objectContaining({
          questions: expect.arrayContaining([
            expect.objectContaining({
              id: 'section_0_q1',
              questionType: 'comprehension',
              difficultyLevel: 3,
              // Note: validationMetadata is not included in the QTI metadata questions array
              // but is preserved in the original Phase 4 input structure
            })
          ])
        })
      })
    );
  });
});
